### ISSUE TITLE
過去の分も含めてコメント

### ISSUE THREAD

**Issue by sfujiwara** [tami888/PE#1]
とりあえず気付いた範囲で。

## Problem 2

* 変数 `tmp` が名前に反して活躍しすぎている
  - `while` 文の条件は `tmp` を使わずに書けるはず
  - `tmp` という後で一時的なものとして使うだけの変数が、最初に堂々と定義されているのがちょっと気持ち悪い感じがする

## Problem 7

* https://github.com/tami888/PE/blob/master/Problem007.py#L17
  - 特に問題ないけど、これで処理が重い `append` を避けたことになっていないのは把握している？

## Problem 8

* 他の問題でも同じことをやっているけれど、何かの最大値を求めるときは調べている最中に最大値だけを保持しておけば良くて、過去に調べた全ての値を残しておく必要はない
  - `list` に大量に `append` 処理をするのを避けられるはず

## Problem 9

* https://github.com/tami888/PE/blob/master/Problem009.py#L14-L15
  - そうじゃない、 `n` が 1 以上の整数だったとしても `c` が負のケースを調べていることに気付いて

## Problem 10

* ちょっと変な関数の分け方している気がする
* https://github.com/tami888/PE/blob/master/Problem010.py#L10
  - `isprime` は何を受け取って何を返す関数か説明をしてほしい
* 速度はそこまで気にしなくても良いとは言ったけれど、もうちょっと速くしてほしいかな
  - 素数を探すとき偶数だけ調べたりしているのは偉いけれど、アルゴリズムのオーダーが違うと致命的に遅くなる
  - 参考までにエラトステネスの篩を実装した fujiwara のコードは 1/1000 くらいの時間で終わるけれども、Project Euler の先の方の問題だとこれでも速度が全然足りなくて乱択アルゴリズム使うことがある

**Comment by tami888** [comment]
レビューありがとうございます！sfujiwaraさんの意見を参考にしてコード修正します。

**Comment by tami888** [comment]
Problem2においてtmpを使わない方向で修正をしました。
Problem7の17行目にでls += [i]としているのでappendと同じことをしていると思います。
Problem9でcが負の値の場合でも調べていたので、負の場合は処理をスキップするように修正しました。

**Comment by tami888** [comment]
全てのissueを分割しましたのでcloseします。
